package priv.mfurmane.szlachtownica.model.simulation.terrain;

public enum SoilType {
//    FERTILE, //generalnie żyzna
//    BLACK, //czarnoziem, zajebista
//    LOAMY, //gliniasto-piaszczysta, dobra pod rolnictwo
//    ALLUVIAL, //odrzeczna, bogata w minerały
//    VOLCANIC, //bardzo żyzna
//    HUMUS_RICH, //próchnica, żyzna
//    LOESS, //lessowa, spoko ale eroduje
//    BASALTIC, //żyzne, ale twarde
//
//    SANDY, //słabo trzyma wodę
//    CLAY, //gliniasta, długo trzyma wodę, trudna
//    SALINE, //zasolona, trochę chujnia i raczej sucho
//    ACIDIC, //kwaśna, trudna
//    ROCKY, //płytka, trudna do orania
//    GRAVELLY, //żwirowe podłoże, luźna i niestabilna
//    HARDPAN, //zbita pod spodem, nie przepuszcza wody
//    PEAT, //torfowa, mokra, ciemna, ale kwaśna i trudna
//    LIMESTONE, //wapienne, zasadowe i skaliste
//    CHALKY, //kredowa, zasadowa i często sucha
//    SHALE_TERRAIN, //łupki, kruche i mało żyzne
//    TANGLED, //pełno splątanych korzeni
//
//    PERMAFROST, //wieczna zmarzlina
//    BARE_CRAG, //gołe skały
//    ASHEN //popioły i kurz, ale nie te żyzne

    PEAT(0.8, 0.7, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.BLACK_OPAL, TerrainResource.GARANDAL, TerrainResource.IRINTAL, TerrainResource.INDICOLITE, TerrainResource.ELERYT, TerrainResource.SUM_METAL, TerrainResource.BLOODSTONE, TerrainResource.IRON, TerrainResource.SOUL_STONE, TerrainResource.VERDELITE, TerrainResource.MERCURY, TerrainResource.COAL, TerrainResource.ECHO_SHARDS, TerrainResource.PEARL, TerrainResource.OLD_BONES, TerrainResource.DRAGON_BONES, TerrainResource.BARNIZYT, TerrainResource.STAR_SHARD, TerrainResource.GLAUCONITE, TerrainResource.AMBER}),
    BARE_CRAG(0.0, 0.0, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.FLAME_STONE, TerrainResource.SUM_METAL, TerrainResource.SLATE, TerrainResource.NIGHT_METAL, TerrainResource.LIMESTONE, TerrainResource.VERDELITE, TerrainResource.MARBLE, TerrainResource.GRANITE, TerrainResource.ECHO_SHARDS, TerrainResource.CHROMIUM, TerrainResource.CHALK, TerrainResource.ALABASTER, TerrainResource.ROCK, TerrainResource.SULFUR, TerrainResource.KASALIT, TerrainResource.MOON_METAL, TerrainResource.STAR_SHARD, TerrainResource.VOID_ORE}),
    FERTILE(1.1, 1.0, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.HELIODOR, TerrainResource.ELERYT, TerrainResource.SUM_METAL, TerrainResource.BLOODSTONE, TerrainResource.VERDELITE, TerrainResource.ECHO_SHARDS, TerrainResource.BARNIZYT, TerrainResource.STAR_SHARD}),
    SALINE(0.3, 1.0, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.FROST_VEIN, TerrainResource.SALT, TerrainResource.LERANIT, TerrainResource.NIGHT_METAL, TerrainResource.VERDELITE, TerrainResource.MERCURY, TerrainResource.ECHO_SHARDS, TerrainResource.VEALITIUM, TerrainResource.PEARL, TerrainResource.SULFUR, TerrainResource.PERIANIT, TerrainResource.KASALIT, TerrainResource.MOON_METAL, TerrainResource.STAR_SHARD, TerrainResource.VOID_ORE}),
    ASHEN(0.0, 0.0, new TerrainResource[]{TerrainResource.BLUE_DIAMOND, TerrainResource.FIRE_OPAL, TerrainResource.TOURMALINE, TerrainResource.BLACK_OPAL, TerrainResource.CITRINE, TerrainResource.IRINTAL, TerrainResource.FLAME_STONE, TerrainResource.MORION, TerrainResource.BLOODSTONE, TerrainResource.AGATE, TerrainResource.BASALT, TerrainResource.SOUL_STONE, TerrainResource.VERDELITE, TerrainResource.OBSIDIAN, TerrainResource.MERCURY, TerrainResource.ECHO_SHARDS, TerrainResource.VEALITIUM, TerrainResource.SULFUR, TerrainResource.AMETHYST, TerrainResource.PERIDOT, TerrainResource.STAR_SHARD}),
    BASALTIC(1.0, 0.6, new TerrainResource[]{TerrainResource.RED_DIAMOND, TerrainResource.BLUE_DIAMOND, TerrainResource.TOURMALINE, TerrainResource.PLATINUM, TerrainResource.SPINEL, TerrainResource.ALEXANDRITE, TerrainResource.SAPPHIRE, TerrainResource.GARANDAL, TerrainResource.SARCOLITE, TerrainResource.CITRINE, TerrainResource.FLAME_STONE, TerrainResource.ELERYT, TerrainResource.IRON, TerrainResource.AGATE, TerrainResource.LERANIT, TerrainResource.BASALT, TerrainResource.CHALCEDONY, TerrainResource.COPPER, TerrainResource.KELTAINUM, TerrainResource.NICKEL, TerrainResource.VERDELITE, TerrainResource.OBSIDIAN, TerrainResource.CUBIC_ZIRCONIA, TerrainResource.GRANITE, TerrainResource.BLUE_GARNET, TerrainResource.ECHO_SHARDS, TerrainResource.CHROMIUM, TerrainResource.DIAMOND, TerrainResource.BARNIZYT, TerrainResource.TOPAZ, TerrainResource.AMETHYST, TerrainResource.BLACK_DIAMOND, TerrainResource.PYROPE, TerrainResource.KASALIT, TerrainResource.MOON_METAL, TerrainResource.PERIDOT, TerrainResource.TURANIT, TerrainResource.STAR_SHARD, TerrainResource.VOID_ORE, TerrainResource.SILVER}),
    HUMUS_RICH(1.0, 1.0, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.DRAVITE, TerrainResource.INDICOLITE, TerrainResource.GROSSULAR, TerrainResource.SUM_METAL, TerrainResource.BLOODSTONE, TerrainResource.MOONSTONE, TerrainResource.VERDELITE, TerrainResource.ECHO_SHARDS, TerrainResource.PEARL, TerrainResource.MORGANITE, TerrainResource.STAR_SHARD, TerrainResource.GLAUCONITE, TerrainResource.AMBER}),
    CHALKY(0.9, 0.9, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.SPINEL, TerrainResource.FROST_VEIN, TerrainResource.CELENIT, TerrainResource.SARCOLITE, TerrainResource.GROSSULAR, TerrainResource.SERENDIBITE, TerrainResource.LEAD, TerrainResource.PHENAKITE, TerrainResource.LIMESTONE, TerrainResource.TAAFFEITE, TerrainResource.FLUORITE, TerrainResource.VERDELITE, TerrainResource.MARBLE, TerrainResource.OBSIDIAN, TerrainResource.ECHO_SHARDS, TerrainResource.LAPIS_LAZULI, TerrainResource.CHALK, TerrainResource.ALABASTER, TerrainResource.PERIANIT, TerrainResource.STAR_SHARD, TerrainResource.ZINC}),
    ROCKY(0.5, 0.5, new TerrainResource[]{TerrainResource.RED_DIAMOND, TerrainResource.BLUE_DIAMOND, TerrainResource.DEMANTOID, TerrainResource.TOURMALINE, TerrainResource.PLATINUM, TerrainResource.SPINEL, TerrainResource.ALEXANDRITE, TerrainResource.NEPHRITE, TerrainResource.SAPPHIRE, TerrainResource.FROST_VEIN, TerrainResource.TIN, TerrainResource.CELENIT, TerrainResource.SARCOLITE, TerrainResource.GARNET, TerrainResource.CITRINE, TerrainResource.FLAME_STONE, TerrainResource.MORION, TerrainResource.GROSSULAR, TerrainResource.SUM_METAL, TerrainResource.SERENDIBITE, TerrainResource.TANZANITE, TerrainResource.SLATE, TerrainResource.IRON, TerrainResource.AMAZONITE, TerrainResource.AGATE, TerrainResource.LERANIT, TerrainResource.TUNGSTEN, TerrainResource.BASALT, TerrainResource.CHALCEDONY, TerrainResource.COPPER, TerrainResource.NIGHT_METAL, TerrainResource.PHENAKITE, TerrainResource.LIMESTONE, TerrainResource.SOUL_STONE, TerrainResource.TAAFFEITE, TerrainResource.JADEITE, TerrainResource.KELTAINUM, TerrainResource.JASPER, TerrainResource.NICKEL, TerrainResource.VERDELITE, TerrainResource.MARBLE, TerrainResource.OBSIDIAN, TerrainResource.CUBIC_ZIRCONIA, TerrainResource.GOLD, TerrainResource.GRANITE, TerrainResource.COAL, TerrainResource.ECHO_SHARDS, TerrainResource.CHROMIUM, TerrainResource.VEALITIUM, TerrainResource.LAPIS_LAZULI, TerrainResource.ZIRCON, TerrainResource.AQUAMARINE, TerrainResource.CHALK, TerrainResource.ALABASTER, TerrainResource.ROCK, TerrainResource.CHRYSOBERYL, TerrainResource.DIAMOND, TerrainResource.TOPAZ, TerrainResource.AMETHYST, TerrainResource.BLACK_DIAMOND, TerrainResource.ALMANDINE, TerrainResource.BERYL, TerrainResource.PERIANIT, TerrainResource.PYROPE, TerrainResource.CYMOPHANE, TerrainResource.PERIDOT, TerrainResource.TURANIT, TerrainResource.STAR_SHARD, TerrainResource.SILVER}),
    HARDPAN(0.8, 0.9, new TerrainResource[]{TerrainResource.DEMANTOID, TerrainResource.TOURMALINE, TerrainResource.CLAY, TerrainResource.CELENIT, TerrainResource.SUM_METAL, TerrainResource.LEAD, TerrainResource.IRON, TerrainResource.LERANIT, TerrainResource.BASALT, TerrainResource.NIGHT_METAL, TerrainResource.NICKEL, TerrainResource.VERDELITE, TerrainResource.MARBLE, TerrainResource.MERCURY, TerrainResource.GRANITE, TerrainResource.COAL, TerrainResource.ECHO_SHARDS, TerrainResource.AQUAMARINE, TerrainResource.ROCK, TerrainResource.CHRYSOBERYL, TerrainResource.ALMANDINE, TerrainResource.BERYL, TerrainResource.KASALIT, TerrainResource.CYMOPHANE, TerrainResource.MOON_METAL, TerrainResource.STAR_SHARD, TerrainResource.VOID_ORE, TerrainResource.ZINC}),
    GRAVELLY(0.6, 0.7, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.PLATINUM, TerrainResource.TIN, TerrainResource.CELENIT, TerrainResource.CITRINE, TerrainResource.FLAME_STONE, TerrainResource.SLATE, TerrainResource.TUNGSTEN, TerrainResource.PHENAKITE, TerrainResource.JASPER, TerrainResource.VERDELITE, TerrainResource.GOLD, TerrainResource.ECHO_SHARDS, TerrainResource.ZIRCON, TerrainResource.ROCK, TerrainResource.PERIANIT, TerrainResource.STAR_SHARD}),
    ALLUVIAL(1.1, 1.2, new TerrainResource[]{TerrainResource.FIRE_OPAL, TerrainResource.TOURMALINE, TerrainResource.PLATINUM, TerrainResource.DRAVITE, TerrainResource.HELIODOR, TerrainResource.SAPPHIRE, TerrainResource.FROST_VEIN, TerrainResource.TIN, TerrainResource.SUM_METAL, TerrainResource.BLOODSTONE, TerrainResource.IRON, TerrainResource.TUNGSTEN, TerrainResource.COPPER, TerrainResource.TAAFFEITE, TerrainResource.SPESSARTINE, TerrainResource.KELTAINUM, TerrainResource.FLUORITE, TerrainResource.VERDELITE, TerrainResource.ONYX, TerrainResource.GOLD, TerrainResource.COAL, TerrainResource.ECHO_SHARDS, TerrainResource.ZIRCON, TerrainResource.PEARL, TerrainResource.KUPARIN, TerrainResource.MORGANITE, TerrainResource.TOPAZ, TerrainResource.PERIANIT, TerrainResource.TURANIT, TerrainResource.STAR_SHARD, TerrainResource.AMBER, TerrainResource.SAND, TerrainResource.SILVER, TerrainResource.RUBELLITE}),
    SHALE_TERRAIN(0.5, 0.7, new TerrainResource[]{TerrainResource.RED_DIAMOND, TerrainResource.EMERALD, TerrainResource.DEMANTOID, TerrainResource.TOURMALINE, TerrainResource.GRANDIDIERITE, TerrainResource.DRAVITE, TerrainResource.ALEXANDRITE, TerrainResource.NEPHRITE, TerrainResource.CLAY, TerrainResource.SAPPHIRE, TerrainResource.GARNET, TerrainResource.SUM_METAL, TerrainResource.SERENDIBITE, TerrainResource.TANZANITE, TerrainResource.LEAD, TerrainResource.SLATE, TerrainResource.IRON, TerrainResource.AMAZONITE, TerrainResource.COPPER, TerrainResource.NIGHT_METAL, TerrainResource.SPESSARTINE, TerrainResource.JADEITE, TerrainResource.KELTAINUM, TerrainResource.VERDELITE, TerrainResource.CUBIC_ZIRCONIA, TerrainResource.GOLD, TerrainResource.COAL, TerrainResource.BLUE_GARNET, TerrainResource.ECHO_SHARDS, TerrainResource.LAPIS_LAZULI, TerrainResource.RUBY, TerrainResource.AQUAMARINE, TerrainResource.ROCK, TerrainResource.CHRYSOBERYL, TerrainResource.KUPARIN, TerrainResource.DIAMOND, TerrainResource.BLACK_DIAMOND, TerrainResource.ALMANDINE, TerrainResource.BERYL, TerrainResource.PYROPE, TerrainResource.CYMOPHANE, TerrainResource.MOON_METAL, TerrainResource.TURANIT, TerrainResource.STAR_SHARD, TerrainResource.ZINC, TerrainResource.SILVER}),
    VOLCANIC(1.2, 0.8, new TerrainResource[]{TerrainResource.RED_DIAMOND, TerrainResource.BLUE_DIAMOND, TerrainResource.FIRE_OPAL, TerrainResource.TOURMALINE, TerrainResource.GRANDIDIERITE, TerrainResource.HELIODOR, TerrainResource.BLACK_OPAL, TerrainResource.GARANDAL, TerrainResource.CITRINE, TerrainResource.FLAME_STONE, TerrainResource.MORION, TerrainResource.ELERYT, TerrainResource.AGATE, TerrainResource.BASALT, TerrainResource.CHALCEDONY, TerrainResource.SOUL_STONE, TerrainResource.MOONSTONE, TerrainResource.JASPER, TerrainResource.VERDELITE, TerrainResource.ONYX, TerrainResource.OBSIDIAN, TerrainResource.MERCURY, TerrainResource.ECHO_SHARDS, TerrainResource.SULFUR, TerrainResource.DIAMOND, TerrainResource.BARNIZYT, TerrainResource.AMETHYST, TerrainResource.BLACK_DIAMOND, TerrainResource.KASALIT, TerrainResource.MOON_METAL, TerrainResource.PERIDOT, TerrainResource.STAR_SHARD, TerrainResource.VOID_ORE, TerrainResource.MALACHITE}),
    PERMAFROST(0.0, 0.0, new TerrainResource[]{TerrainResource.NEPHRITE, TerrainResource.FROST_VEIN, TerrainResource.GARANDAL, TerrainResource.BLOODSTONE, TerrainResource.LERANIT, TerrainResource.NIGHT_METAL, TerrainResource.SOUL_STONE, TerrainResource.JADEITE, TerrainResource.NICKEL, TerrainResource.ECHO_SHARDS, TerrainResource.VEALITIUM, TerrainResource.OLD_BONES, TerrainResource.DRAGON_BONES, TerrainResource.STAR_SHARD}),
    ACIDIC(0.5, 0.7, new TerrainResource[]{TerrainResource.EMERALD, TerrainResource.TOURMALINE, TerrainResource.GRANDIDIERITE, TerrainResource.FROST_VEIN, TerrainResource.IRINTAL, TerrainResource.INDICOLITE, TerrainResource.TANZANITE, TerrainResource.LERANIT, TerrainResource.NIGHT_METAL, TerrainResource.MOONSTONE, TerrainResource.SPESSARTINE, TerrainResource.VERDELITE, TerrainResource.ONYX, TerrainResource.ECHO_SHARDS, TerrainResource.RUBY, TerrainResource.MORGANITE, TerrainResource.PERIANIT, TerrainResource.KASALIT, TerrainResource.MOON_METAL, TerrainResource.STAR_SHARD, TerrainResource.VOID_ORE, TerrainResource.GLAUCONITE, TerrainResource.RUBELLITE}),
    BLACK(1.2, 1.2, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.ELERYT, TerrainResource.SUM_METAL, TerrainResource.BLOODSTONE, TerrainResource.VERDELITE, TerrainResource.ECHO_SHARDS, TerrainResource.OLD_BONES, TerrainResource.DRAGON_BONES, TerrainResource.BARNIZYT, TerrainResource.PERIANIT, TerrainResource.STAR_SHARD}),
    LOESS(0.95, 0.9, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.SALT, TerrainResource.PHENAKITE, TerrainResource.FLUORITE, TerrainResource.JASPER, TerrainResource.VERDELITE, TerrainResource.ECHO_SHARDS, TerrainResource.STAR_SHARD, TerrainResource.GLAUCONITE}),
    SANDY(0.7, 1.0, new TerrainResource[]{TerrainResource.TOURMALINE, TerrainResource.IRINTAL, TerrainResource.MORION, TerrainResource.SALT, TerrainResource.LERANIT, TerrainResource.JASPER, TerrainResource.VERDELITE, TerrainResource.ECHO_SHARDS, TerrainResource.ZIRCON, TerrainResource.KUPARIN, TerrainResource.STAR_SHARD, TerrainResource.AMBER, TerrainResource.SAND}),
    CLAY(0.8, 0.7, new TerrainResource[]{TerrainResource.EMERALD, TerrainResource.DEMANTOID, TerrainResource.TOURMALINE, TerrainResource.DRAVITE, TerrainResource.NEPHRITE, TerrainResource.CLAY, TerrainResource.BLACK_OPAL, TerrainResource.GARNET, TerrainResource.SALT, TerrainResource.TANZANITE, TerrainResource.LEAD, TerrainResource.SLATE, TerrainResource.IRON, TerrainResource.COPPER, TerrainResource.NIGHT_METAL, TerrainResource.SPESSARTINE, TerrainResource.JADEITE, TerrainResource.KELTAINUM, TerrainResource.VERDELITE, TerrainResource.ONYX, TerrainResource.MERCURY, TerrainResource.GOLD, TerrainResource.COAL, TerrainResource.BLUE_GARNET, TerrainResource.ECHO_SHARDS, TerrainResource.RUBY, TerrainResource.KUPARIN, TerrainResource.TOPAZ, TerrainResource.PERIANIT, TerrainResource.PYROPE, TerrainResource.TURANIT, TerrainResource.STAR_SHARD, TerrainResource.MALACHITE, TerrainResource.ZINC, TerrainResource.SILVER, TerrainResource.RUBELLITE}),
    LIMESTONE(0.9, 0.8, new TerrainResource[]{TerrainResource.EMERALD, TerrainResource.TOURMALINE, TerrainResource.SPINEL, TerrainResource.FROST_VEIN, TerrainResource.CELENIT, TerrainResource.SARCOLITE, TerrainResource.GROSSULAR, TerrainResource.SERENDIBITE, TerrainResource.SALT, TerrainResource.LEAD, TerrainResource.PHENAKITE, TerrainResource.LIMESTONE, TerrainResource.TAAFFEITE, TerrainResource.FLUORITE, TerrainResource.VERDELITE, TerrainResource.MARBLE, TerrainResource.ECHO_SHARDS, TerrainResource.LAPIS_LAZULI, TerrainResource.RUBY, TerrainResource.CHALK, TerrainResource.ALABASTER, TerrainResource.PERIANIT, TerrainResource.MOON_METAL, TerrainResource.STAR_SHARD, TerrainResource.MALACHITE, TerrainResource.ZINC}),
    LOAMY(1.0, 1.2, new TerrainResource[]{TerrainResource.FIRE_OPAL, TerrainResource.TOURMALINE, TerrainResource.GRANDIDIERITE, TerrainResource.DRAVITE, TerrainResource.CLAY, TerrainResource.HELIODOR, TerrainResource.BLACK_OPAL, TerrainResource.GARNET, TerrainResource.INDICOLITE, TerrainResource.SUM_METAL, TerrainResource.IRON, TerrainResource.MOONSTONE, TerrainResource.VERDELITE, TerrainResource.BLUE_GARNET, TerrainResource.ECHO_SHARDS, TerrainResource.ZIRCON, TerrainResource.KUPARIN, TerrainResource.MORGANITE, TerrainResource.STAR_SHARD, TerrainResource.MALACHITE, TerrainResource.AMBER, TerrainResource.SAND, TerrainResource.RUBELLITE}),
    TANGLED(1.2, 0.6, new TerrainResource[]{TerrainResource.DEMANTOID, TerrainResource.TOURMALINE, TerrainResource.CELENIT, TerrainResource.IRINTAL, TerrainResource.ELERYT, TerrainResource.SUM_METAL, TerrainResource.BLOODSTONE, TerrainResource.NIGHT_METAL, TerrainResource.SOUL_STONE, TerrainResource.VERDELITE, TerrainResource.ECHO_SHARDS, TerrainResource.BARNIZYT, TerrainResource.STAR_SHARD, TerrainResource.AMBER});

    private final TerrainResource[] resources;
    private final Double fertility;
    private final Double plantingEasiness;

    public TerrainResource[] getResources() {
        return resources;
    }

    public Double getFertility() {
        return fertility;
    }

    public Double getPlantingEasiness() {
        return plantingEasiness;
    }

    SoilType(Double fertility, Double plantingEasiness, TerrainResource[] resources) {
        this.resources = resources;
        this.fertility = fertility;
        this.plantingEasiness = plantingEasiness;
    }
}
